### ISSUE TITLE
Error During Validation

### ISSUE THREAD

**Issue by JJayaL** [andvg3/Grasp-Anything#13]
I am getting the following error during validation:
root        : INFO     Validating...
Traceback (most recent call last):
  File "/home/jjayalekshmi/workspaces/Grasp-Anything/train_network.py", line 348, in <module>
    run()
  File "/home/jjayalekshmi/workspaces/Grasp-Anything/train_network.py", line 330, in run
    test_results = validate(net, device, val_data, args.iou_threshold)
  File "/home/jjayalekshmi/workspaces/Grasp-Anything/train_network.py", line 128, in validate
    val_data.dataset.get_gtbb(didx, rot, zoom_factor),
  File "/home/jjayalekshmi/workspaces/Grasp-Anything/utils/data/cornell_data.py", line 45, in get_gtbb
    gtbbs.rotate(rot, center)
  File "/home/jjayalekshmi/workspaces/Grasp-Anything/utils/dataset_processing/grasp.py", line 48, in <lambda>
    return lambda *args, **kwargs: list(map(lambda gr: getattr(gr, attr)(*args, **kwargs), self.grs))
  File "/home/jjayalekshmi/workspaces/Grasp-Anything/utils/dataset_processing/grasp.py", line 48, in <lambda>
    return lambda *args, **kwargs: list(map(lambda gr: getattr(gr, attr)(*args, **kwargs), self.grs))
  File "/home/jjayalekshmi/workspaces/Grasp-Anything/utils/dataset_processing/grasp.py", line 405, in rotate
    self.points = ((np.dot(R, (self.points - c).T)).T + c).astype(int)
ValueError: shapes (2,2,1) and (2,4) not aligned: 1 (dim 2) != 2 (dim 0)

Please let me know how i can solve it.

**Comment by jfayyad** [comment]
I am getting a similar error 
    R = np.array(
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

**Comment by JJayaL** [comment]
I was able to solve this error by downgrading my python and numpy. I an currently using python 3.8 and numpy 1.21.1.

**Comment by JJayaL** [comment]
I was able to solve this error by downgrading my python and numpy. I am currently using python 3.8 and numpy 1.21.1.

**Comment by xiaoming-gong** [comment]
> I was able to solve this error by downgrading my python and numpy. I am currently using python 3.8 and numpy 1.21.1.

That's right. Thank you very much!
